### ISSUE TITLE
Not Issue - How to use it on multiple machines.

### ISSUE THREAD

**Issue by kishor10d** [Mazzzy/chatApp#1]
Application running successfully on single machine. I open ```file:///D:/chatApp/public/index.html``` and started chat. But if I wan to test it on my LAN, how can other machines will join?

By using IP address others can join me but I need to create a server which accessible over LAN. How to do it?

**Comment by Mazzzy** [comment]
You can run the server.js on your machine and access it over LAN for the given port

**Comment by kishor10d** [comment]
Which url I have to hit on browser?

is there any localhost?? I tried hitting ```http://myip:1337``` on my own machine but its not working.

**Comment by Mazzzy** [comment]
It can be run through local html file only.
We need to make it run through server (add express / or serve the index file through server.js).
Then you can have url and you can use it over intranet

**Comment by Mazzzy** [comment]
You can add this to your server.js file

var express = require('express');
var app = express();
var path = require('path');

// viewed at http://localhost:8080

app.get('/', function(req, res) {
    res.sendFile(path.join(__dirname + '/index.html'));
});

app.listen(8080);

**Comment by Mazzzy** [comment]
You can add this to your server.js file

var express = require('express');
var app = express();
var path = require('path');

// viewed at http://localhost:8080

app.get('/', function(req, res) {
res.sendFile(path.join(__dirname + '/public/index.html'));
});

app.listen(8080);

**Comment by Mazzzy** [comment]
Hope that helps!

**Comment by kishor10d** [comment]
Can you please add the same thing in your code? Because, nobody will try the chat on their own (single) machine.
This way you can update your repository too. I have same thing working with PHP, it is realtime notification, wall post update like facebook wall. (but all client at the same time, not pubsub).

**Comment by Mazzzy** [comment]
Agreed, the app has been developed for demonstration purpose and can be customised as per the requirement. So one can use it to have kick start and modify it accordingly.

Feel free to use and customise!

**Comment by Mazzzy** [comment]
I have added express based feature to serve client.
You can navigate to 'http://localhost:9000/' and see the app running!

You can also use it over intranet just need to replace localhost with <your ip>.
Enjoy :)

**Comment by Mazzzy** [comment]
I have added express based feature to serve client.
You can navigate to 'http://localhost:9000/' and see the app running!

You can also use it over intranet just need to replace localhost with <your ip>.
Enjoy :)

**Comment by Mazzzy** [comment]
I have added express based feature to serve client.
You can navigate to 'http://localhost:9000/' and see the app running!

You can also use it over intranet just need to replace localhost with 'your_ip'.
Enjoy :)

**Comment by kishor10d** [comment]
@Mazzzy : Hey, its working great! After pulling new commit, the other (client) machine is not connecting to the websocket just because of following line (in ```chatApp/public/client.js : line 38```)
```var connection = new WebSocket('ws://127.0.0.1:1337');```

So I changed it with my lan ip like ```var connection = new WebSocket('ws://192.168.1.110:1337');```, so that websocket will run on my ip (server).
And its working great now.
Actually I have same thing developed using PHP websocket library - https://github.com/kishor10d/CodeIgniter-Ratchet-Websocket, please give it a try if you want.
